import initAuth from '@/firebase/firebaseInitAuth';
import './globals.scss'
import type { Metadata } from 'next'
import { Poppins } from 'next/font/google';
import React from "react";

const poppinsFont = Poppins(
  {
    weight: ['200','300','400','500','600','700','800','900'],
    subsets: ['latin'],
    variable: '--font-poppins',
  },
  
);

export const metadata: Metadata = {
  title: 'Rockster',
  description: 'Generated by create next app',
}

initAuth();

export default function RootLayout({ children }: {children: React.ReactNode }) {
  return (
    <html lang='en'>
      <head />
      <body className={`${poppinsFont.variable}`}>
            {children}
      </body>
    </html>
  );
}
